name: build java project
on:
    workflow_dispatch:
jobs:
    build:
        uses: chaitanyabhogadi/Resuable_workflow_29a/.github/workflows/build.yml@v1_java
        with: 
            java_version: '21'
            maven_command: 'package'
